name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Adjust this to your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./backend # Specify the correct directory for package.json

      - name: Build the project
        run: npm run build
        working-directory: ./backend # Ensure it points to the correct directory

      - name: Run tests
        run: npm test
        working-directory: ./backend # Ensure it points to the correct directory
